name: "callmebot-notifier"
description: "Send notifications from GitHub Actions"
author: "F3rr1gn0"
branding:
  icon: "bell"
  color: "blue"
inputs:
  message:
    required: true
    description: "Message to send"
  channel:
    required: false
    description: "Optional channel preset"
runs:
  using: "node24"
  main: "dist/index.js"